# Generated by Django 4.2 on 2026-03-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("viewer", "View Only"),
                            ("editor", "Can Edit"),
                            ("admin", "Full Admin Access"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Automatic revocation date for time-limited shares",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete - user can deactivate without losing history",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces_shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="notes.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserOAuthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("github", "GitHub")],
                        max_length=50,
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(
                        help_text="Unique identifier from OAuth provider",
                        max_length=255,
                    ),
                ),
                (
                    "provider_email",
                    models.EmailField(
                        help_text="Email from OAuth provider", max_length=254
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="OAuth access token for API calls (encrypted in production)"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="OAuth refresh token (encrypted in production)",
                        null=True,
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("viewer", "View Only"),
                            ("editor", "Can Edit"),
                            ("admin", "Full Admin Access"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Automatic revocation date for time-limited shares",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete - user can deactivate without losing history",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="notes.note",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborativeEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("insert", "Insert text"),
                            ("delete", "Delete text"),
                            ("replace", "Replace text"),
                            ("format", "Change formatting"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(help_text="Character position in note content"),
                ),
                (
                    "content_before",
                    models.TextField(help_text="Content before the operation"),
                ),
                (
                    "content_after",
                    models.TextField(help_text="Content after the operation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conflict_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this edit has been flagged as conflicting and resolved",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workspaceshare",
            index=models.Index(
                fields=["shared_with", "is_active"],
                name="sharing_wor_shared__9af8d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceshare",
            index=models.Index(
                fields=["workspace", "is_active"], name="sharing_wor_workspa_8c211b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceshare",
            unique_together={("workspace", "shared_with")},
        ),
        migrations.AlterUniqueTogether(
            name="useroauthprovider",
            unique_together={("provider", "provider_user_id")},
        ),
        migrations.AddIndex(
            model_name="noteshare",
            index=models.Index(
                fields=["shared_with", "is_active"],
                name="sharing_not_shared__c00ff7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noteshare",
            index=models.Index(
                fields=["note", "is_active"], name="sharing_not_note_id_17516c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noteshare",
            unique_together={("note", "shared_with")},
        ),
        migrations.AddIndex(
            model_name="collaborativeedit",
            index=models.Index(
                fields=["note", "created_at"], name="sharing_col_note_id_8362ca_idx"
            ),
        ),
    ]
