# Generated by Django 4.2 on 2026-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteshare",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Whether the shared user has hidden this note from their main view",
            ),
        ),
    ]
