# Generated by Django 4.2 on 2026-10-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0002_noteshare_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceshare",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Whether the shared user has hidden this workspace from their main view",
            ),
        ),
    ]
