# Generated by Django 4.2 on 2026-03-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
        migrations.AddField(
            model_name="note",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="note",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.workspace",
            ),
        ),
    ]
