# Generated by Django 4.2 on 2026-10-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_remove_note_content_note_body_alter_note_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="notes.workspace",
            ),
        ),
    ]
