# Generated by Django 4.2 on 2026-10-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_is_favorite_alter_note_workspace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-custom_sort_index", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="note",
            name="custom_sort_index",
            field=models.BigIntegerField(default=0),
        ),
    ]
